version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: local-mysql
    networks:
      mysql-network:
        ipv4_address: 174.101.101.101
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "covid-tracker"

  adminer:
    image: adminer
    container_name: local-adminer
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: "local-mysql"
      ADMINER_DESIGN: "dracula"
      ADMINER_PLUGINS: "tables-filter tinymce"
    networks:
      mysql-network:
        ipv4_address: 174.101.101.102

networks:
  mysql-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 174.101.101.0/24